// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://trjiaifxzhjqlxijnbex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyamlhaWZ4emhqcWx4aWpuYmV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTQ1ODIsImV4cCI6MjA3Mjk5MDU4Mn0.2bRi0ELsubZXmQiTzUhTpzQBHe8Sy_VOaOcEsovuD6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);